### ISSUE TITLE
Definir los parámetros del problema de optimización y método numérico

### ISSUE THREAD

**Issue by jesusmb230795** [optimizacion-2-2022-gh-classroom/practica-2-primera-parte-joelitam2021#2]

**Comment by AideJGC** [comment]
Se realizó la selección de parámeros a optimizar, se tranajo en el notebook [Parametros_optimizar.ipynb](https://github.com/optimizacion-2-2022-gh-classroom/practica-2-primera-parte-joelitam2021/blob/main/notebooks/Parametros_optimizar.ipynb)
